name: flutter_hylid_bridge
description: Flutter wrapper for Hylid Bridge SDK. Provides seamless integration with Hylid's payment, authentication, and UI services on web with automatic script injection.
version: 0.0.1
homepage: https://github.com/hanialkhaffaf/hylid_flutter_sdk
repository: https://github.com/hanialkhaffaf/hylid_flutter_sdk
issue_tracker: https://github.com/hanialkhaffaf/hylid_flutter_sdk/issues
documentation: https://github.com/hanialkhaffaf/hylid_flutter_sdk#readme

topics:
  - payment
  - hylid
  - bridge
  - authentication
  - web

platforms:
  web:

environment:
   sdk: '>=3.10.0 <4.0.0'
   flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      web:
