name: flutter_hylid_bridge
description: Flutter wrapper for Hylid-Bridge JavaScript SDK
version: 0.0.1
homepage: https://github.com/hanialkhaffaf/flutter_hylid_bridge
repository: https://github.com/hanialkhaffaf/flutter_hylid_bridge
issue_tracker: https://github.com/hanialkhaffaf/flutter_hylid_bridge/issues
documentation: https://github.com/hanialkhaffaf/flutter_hylid_bridge#readme

topics:
  - payment
  - authentication
  - ui
  - web

platforms:
  web:

environment:
   sdk: '>=3.10.0 <4.0.0'
   flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      web:
